#!/usr/bin/perl -w

# Generate usys.S, the stubs for syscalls.

print "# generated by usys.pl - do not edit\n";
print "#include \"kernel/syscall.h\"\n";

sub entry {
    my $name = shift;
    print ".global $name\n";
    print "${name}:\n";
    print " li a7, SYS_${name}\n";   # Load syscall number into a7
    print " ecall\n";                 # Perform the ecall instruction to invoke syscall
    print " ret\n";                  # Return after syscall
}
    
entry("fork");
entry("exit");
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("fstat");
entry("link");
entry("mkdir");
entry("chdir");
entry("trace");  # This is where you add the trace syscall entry
entry("dup");
entry("getpid");
entry("sbrk");
entry("sleep");
entry("uptime");
